# Generated by Django 4.1.4 on 2022-12-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'backlog'), ('todo', 'todo'), ('working', 'working'), ('done', 'done')], default='backlog', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
