# Generated by Django 4.1.4 on 2022-12-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_task_status_alter_task_target_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='target_details',
            new_name='task_details',
        ),
    ]
