# Generated by Django 4.1.4 on 2023-01-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_historicaltask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
    ]
