# Generated by Django 4.1.4 on 2023-01-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_historicaltask_alter_historicaltaskcomment_task_and_more'),
        ('project', '0003_remove_task_assignee_remove_task_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
