# Generated by Django 4.1.4 on 2022-12-14 04:07

import app.storage
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_file_uploaded_date_file_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, storage=app.storage.OverwriteStorage(), upload_to=project.models.user_project_directory_path),
        ),
    ]
