# Generated by Django 4.1.4 on 2022-12-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('olp_view_project', 'OLP can view project')]},
        ),
    ]
