# Generated by Django 4.1.4 on 2022-12-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('olp_view_project', 'OLP can view project'), ('olp_change_project', 'OLP can change project'), ('olp_delete_project', 'OLP can delete project'), ('olp_manage_collaborator_project', 'OLP can change collaborator project')]},
        ),
    ]
