# Generated by Django 4.1.4 on 2022-12-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('olp_view_project', 'OLP can view project'), ('olp_change_project', 'OLP can manage project'), ('olp_delete_project', 'OLP can delete project'), ('olp_manage_collaborator_project', 'OLP can change collaborator project'), ('olp_manage_file_project', 'OLP can manage file project'), ('olp_delete_file_project', 'OLP can delete file project'), ('olp_manage_task_project', 'OLP can manage task project'), ('olp_delete_task_project', 'OLP can delete task project')]},
        ),
    ]
