# Generated by Django 4.1.4 on 2022-12-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('olp_view_project', 'OLP can view project'), ('olp_update_project', 'OLP can update project'), ('olp_delete_project', 'OLP can delete project'), ('olp_view_collaborator', 'OLP can view project'), ('olp_add_collaborator_project', 'OLP can add collaborator project'), ('olp_update_collaborator_project', 'OLP can update collaborator project'), ('olp_delete_collaborator_project', 'OLP can delete collaborator project'), ('olp_view_file_project', 'OLP can view file project'), ('olp_add_file_project', 'OLP can add file project'), ('olp_update_file_project', 'OLP can update file project'), ('olp_delete_file_project', 'OLP can delete file project'), ('olp_view_task_project', 'OLP can view task project'), ('olp_add_task_project', 'OLP can add task project'), ('olp_update_task_project', 'OLP can update task project'), ('olp_delete_task_project', 'OLP can delete task project')]},
        ),
    ]
