# Generated by Django 4.1.4 on 2022-12-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('olp_view_project', 'OLP can view project'), ('olp_update_project', 'OLP can update project'), ('olp_delete_project', 'OLP can delete project'), ('olp_view_collaborator_project', 'OLP can view project'), ('olp_add_collaborator_project', 'OLP can add collaborator project'), ('olp_update_collaborator_project', 'OLP can update collaborator project'), ('olp_delete_collaborator_project', 'OLP can delete collaborator project')]},
        ),
    ]
