version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devuser
      - POSTGRES_DB=devdb

  redis:
    image: redis:alpine3.16
    container_name: redis

  celery:
    restart: always
    build: ./app
    container_name: celery
    command: celery -A app worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - db

  celery-beat:
    restart: always
    build: ./app
    command: celery -A app beat -l info
    container_name: celery-beat
    env_file:
      - ./.env.dev
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data: