# Generated by Django 4.1.4 on 2023-01-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
