# Generated by Django 4.1.4 on 2023-02-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='langcode_tags',
        ),
    ]
